sudo: required

services:
  - docker

branches:
  only:
  - master

script:
  - docker login --username "${DOCKERHUB_USER}" --password "${DOCKERHUB_PASS}"
  - ./build.sh node-basic
  - ./build.sh node-chrome

